### ISSUE TITLE
Object comparison with #==

### ISSUE THREAD

**Issue by t6d** [t6d/smart_properties#41]
Two `SmartProperties`-enabled objects should be considered equal if they have their respective properties are equal.

**Comment by amomchilov** [comment]
Hey @t6d, may I ask why this was closed? It doesn't look like this was ever implemented:

```ruby
class C
  include SmartProperties

  property! :a, accepts: Integer
  property! :b, accepts: Integer
end

C.new(a: 1, b: 2) == C.new(a: 1, b: 2) # => false
C.new(a: 1, b: 2).method(:==).owner # => BasicObject
```

I have a module I wrote that can be plugged in to add value-based equality. Would be interested in my contributing it?
