### ISSUE TITLE
split `accepts:` into two separate keywords

### ISSUE THREAD

**Issue by exterm** [t6d/smart_properties#60]
Currently, `accepts:` does two things that conflict with each other.

`accepts: [true, false]` is obvious.
`accepts: String` works great too.
But what about `accepts: [String]`? This only allows one value, which might or might not be surprising dependent on your understanding of SmartProperties. Why not split into different keywords?

E.g. `accepts: [true, false]`, `accepts: ->(value) { value.odd? }`, in which case the keyword could also be renamed to `accepts_values`, and `accepts_type: [String]` which would be accepting an Array of String values.

**Caveats**
> Is this introducing additional complexity just for one edge case?

I don't think so, it mainly makes existing behavior more explicit - the added behavior is a nice side effect
> what about other complex types? Should we allow `accepts: {String => Integer}` too?

Good point, I think we should. Alternatively, we could allow expressing complex types differently, like providing builtin methods.

**Comment by t6d** [comment]
Interesting, but I like to think that a more flexible solution could be

```
property :flag, accepts: types(Integer, String)

def types(types)
  ->(value) { types.any? { |type| value.kind_of?(type) } }
end
```

This solution would also push this out of the scope of SmartProperties. Wether `types` should be a `Kernel`-level function or housed in a module would be a project decision.

**Comment by exterm** [comment]
I like that!
